language: node_js
node_js:
  - "10"
  - "lts/*"
cache:
  yarn: true
  directories:
    - "node_modules"
jobs:
  include:
    - stage: "Lints"
      name: "typescript"
      script: "yarn run typecheck"
    - stage: "Lints"
      name: "eslint"
      script: "yarn run eslint"
stages:
  - "Lints"
  - "Test"
